# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='ScaffoldContentPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.BasePage')),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.basepage',),
        ),
        migrations.CreateModel(
            name='IconField',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.BaseField')),
                ('faIcon', models.CharField(max_length=50)),
                ('faIconType', models.CharField(default='fab', max_length=50)),
                ('isVisible', models.BooleanField(default=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.basefield',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.BaseField')),
                ('url', models.ImageField(upload_to='uploads/imgs/')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.basefield',),
        ),
        migrations.CreateModel(
            name='PageField',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.BaseField')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.basefield',),
        ),
        migrations.CreateModel(
            name='ScaffoldPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.BasePage')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.basepage',),
        ),
        migrations.AddField(
            model_name='scaffoldcontentpages',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaffold_section', to='modularweb.BasePage'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_modularweb.basepage_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='basefield',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_modularweb.basefield_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='LinkField',
            fields=[
                ('pagefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.PageField')),
                ('order_link', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.pagefield',),
        ),
        migrations.CreateModel(
            name='SimpleField',
            fields=[
                ('pagefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.PageField')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.pagefield',),
        ),
        migrations.AddField(
            model_name='scaffoldcontentpages',
            name='scaffold_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='modularweb.ScaffoldPage'),
        ),
        migrations.AddField(
            model_name='pagefield',
            name='basePage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modularweb.BasePage'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modularweb.Image'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('linkfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.LinkField')),
                ('target', models.URLField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.linkfield',),
        ),
        migrations.CreateModel(
            name='HeaderPageField',
            fields=[
                ('simplefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.SimpleField')),
                ('fieldType', models.CharField(choices=[('MF', 'Main field (h2)'), ('SF', 'Sub field (h3)')], default='MF', max_length=2)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.simplefield',),
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('linkfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modularweb.LinkField')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modularweb.BasePage')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('modularweb.linkfield',),
        ),
    ]
